### PR TITLE
[BITAU-192] Fix Empty Space at Top Appearing on Pull to Refresh

### PR DESCRIPTION
**Pull request by brant-livefront**
## 🎟️ Tracking

[BITAU-192](https://livefront.atlassian.net/browse/BITAU-192)

## 📔 Objective

This PR fixes a bug that Luke noted where a pull-to-refresh can leave a small space at the top. I did a bunch of research/testing and it seems that this is caused because while the `.refreshable` action is `async`, it can be cancelled. Since our action performs `.refresh` which calls `streamItemList()`, which creates a new `for await` loop, it never really terminates the initial call, leaving it to be cancelled. When it gets cancelled, there seems to be an issue with updating the view, leaving the space at the top. Any view related action will clean up and fix the view (e.g. toast going away, tapping a row, scrolling a bit, etc), but the space remains until something happens to "wake up" the view.

The fix here is to wrap the `await store.perform(.refresh)` in it's own `Task`. This lets the refresh action complete and leave the Task to stream the item list. Since the `.refreshable` action completes, it updates the view.

### Testing Notes
- To make sure you see the issue, make sure you have enough codes in your list. It seems to be much more reproducible with a larger number of codes.
- I do think this makes the view a bit more "jumpy" in my testing because the refresh now finishes so quickly. I'd love feedback on if we think it's worth it to make this fix, or leave the potential space issue.

### Before the fix, showing the issue of space at the top:
https://github.com/user-attachments/assets/a000611e-12bb-45c9-ad4c-b22bffddaebb

### With the fix in the new code:
https://github.com/user-attachments/assets/9aa98bfa-688e-43b9-8d32-7753d954b555

## ⏰ Reminders before review

- Contributor guidelines followed
- All formatters and local linters executed and passed
- Written new unit and / or integration tests where applicable
- Protected functional changes with optionality (feature flags)
- Used internationalization (i18n) for all UI strings
- CI builds passed
- Communicated to DevOps any deployment requirements
- Updated any necessary documentation (Confluence, contributing docs) or informed the documentation team

## 🦮 Reviewer guidelines

- 👍 (`:+1:`) or similar for great changes
- 📝 (`:memo:`) or ℹ️ (`:information_source:`) for notes or general info
- ❓ (`:question:`) for questions
- 🤔 (`:thinking:`) or 💭 (`:thought_balloon:`) for more open inquiry that's not quite a confirmed issue and could potentially benefit from discussion
- 🎨 (`:art:`) for suggestions / improvements
- ❌ (`:x:`) or ⚠️ (`:warning:`) for more significant problems or concerns needing attention
- 🌱 (`:seedling:`) or ♻️ (`:recycle:`) for future improvements or indications of technical debt
- ⛏ (`:pick:`) for minor or nitpick changes

### CODE REVIEW

**Review by KatherineInCode — COMMENTED** [review]
🤔 From a code perspective this looks fine to me, but I'm not sure I like the jumpiness of the UX. Might it be possible to change the behavior of `.refresh` to cancel a streaming-item-list task that might be hanging out there already and/or refresh the view somehow?

**Comment by brant-livefront** [comment]
> 🤔 From a code perspective this looks fine to me, but I'm not sure I like the jumpiness of the UX. Might it be possible to change the behavior of `.refresh` to cancel a streaming-item-list task that might be hanging out there already and/or refresh the view somehow?

I did try to refactor the streamItemList to store a Task in the ItemListProcessor and then cancel that Task and re-build it when we get another call to that method. That means we don't need to wrap the `.refresh` call in the view. Unfortunately, in my testing that resulted in the same jumpiness as this, so I abandoned that refactor because I wasn't comfortable changing so much to get the same outcome.

**Comment by brant-livefront** [comment]
@KatherineInCode Emily had suggested preserving the large titles as a design change which also has the effect of fixing the jumpiness we were seeing in the title. I've refactored to that design. It's a bit of a hack (adding a view to move the scrolling down below the nav bar), but it does seem to be stable ([StackOverflow from 2019](https://stackoverflow.com/a/58870842) was the basis for this). There's the risk of it not continuing in future iOS releases, but I do think it seems consistent going backwards and Authenticator will be getting the reskin that the PM app is getting eventually.

Here's an updated video of it in action. Emily has given this her 👍 
https://github.com/user-attachments/assets/70489e1f-d949-4435-bb41-fc4dbdcb16ec

One last note is that a lot of screenshots changed. Mostly due to the fact that previously they didn't have the primary color background (I think because of how we're adding them in the preview). Visually, this shouldn't have changed much in practice, but I'd love an extra bit of scrutiny there. 👍

**Comment by KatherineInCode** [comment]
Seems reasonable, though let's get the conflicts managed

**Review by KatherineInCode — APPROVED** [review]

**Pull request merged**
